# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/text_db.rb'

Hoe.spec('text_db', TextDb::VERSION) do |p|
  p.rubyforge_name = 'text_dbx' # if different than lowercase project name
  p.developer('David Kamphausen', 'david.kamphausen76@googlemail.com') #FIX@example.com')
end

# vim: syntax=Ruby
